### ISSUE TITLE
Other project types?

### ISSUE THREAD

**Issue by DavidFrahm** [bradcypert/ignite#1]
I see how this project is very useful, but is it only for Meteor or are you willing to accept pull requests for other frameworks or project types?

I'd love to try this out for AngularJS and Ionic projects.

**Comment by bradcypert** [comment]
@DavidFrahm I'm completely open to scaffolding for any Javascript based applications right now. I'm looking to get a good feel for the best way to template angular apps, ember apps, backbone apps, and express apps. If you're interested in helping, feel free to fork the branch, add a template to the templates directory, and submit a pull-request.

You can & should use the meteor template as a template for your template ;)

**Comment by bradcypert** [comment]
Created a template for React scaffolding for now. I'll be making more in the future and you can too!

For now, going to close this issue.
