### ISSUE TITLE
Way to filter listed templates

### ISSUE THREAD

**Issue by bradcypert** [bradcypert/ignite#20]
As we're adding more and more templates, we probably should find a good way to allow people to search for certain templates. Perhaps adding keywords onto the template.json files and allowing people to say something like...

`ignite list cms` and this would list all the templates with the CMS keyword.

Food for thought.

**Comment by wookiecooking** [comment]
:+1:  We could also add a fuzzy search to search the description as well.

**Comment by bradcypert** [comment]
My only fear is that template writers may not put something users would search as the description.
