### ISSUE TITLE
Linting and tests

### ISSUE THREAD

**Issue by wookiecooking** [bradcypert/ignite#6]
Would like to see some tests. I could pull request a simple build with mocha/jslint using gulp. Can create some basic tests as well.

**Comment by bradcypert** [comment]
Any help is appreciated. I'm actually working on cleaning/converting the JS to Ecmascript6. It's pretty bad currently, but gets the job done. I think tests would be great once we hit ES6.

**Comment by wookiecooking** [comment]
Cool, id be happy to help with that. I have experience with es6 as well if help is needed. Was there consideration of jumping to io.js support only? or maybe using some like babel?

**Comment by bradcypert** [comment]
I'm currently using babel on my branch. Open to other suggestions though.

**Comment by bradcypert** [comment]
Taken care of in a previous pull request by @wookiecooking
