### ISSUE TITLE
Create flag for different templates path

### ISSUE THREAD

**Issue by wookiecooking** [bradcypert/ignite#7]
I think a cool feature would be for users to be able to store their templates in a different path. Where they could pass a path to the templates location. 

This would allow users to add their own templates without filling up the core source with configs, and maybe create a separate repo for them.

**Comment by bradcypert** [comment]
We actually added this in a previous release. Check the notes at the bottom of the readme! :)

**Comment by wookiecooking** [comment]
:+1: sorry I passed over that when I was looking at source. I'll close.

**Comment by bradcypert** [comment]
No worries. Source is a mess currently. Working on cleaning it up right now.
